{
 "title": "Temperature Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Raspberry Pi Monitoring\n**Static IP is 192.168.1.134**"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 3 },
   "options": {
    "content": "# Internet Speed\nThis could be wireless or wired, depending on how th device is connected to the network."
   }
  },
  {
   "title": "Download and Upload Speeds",
   "type": "timeseries",
   "description": "This is running the speedtest-cli python library",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "query": "from(bucket: \"temp-monitor-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"speedtest\")\r\n  |> filter(fn: (r) => r._field == \"download\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean_download\")"
    },
    {
     "query": "from(bucket: \"temp-monitor-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"speedtest\")\r\n  |> filter(fn: (r) => r._field == \"upload\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean_upload\")"
    }
   ]
  },
  {
   "title": "Ping",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "query": "from(bucket: \"temp-monitor-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"speedtest\")\r\n  |> filter(fn: (r) => r._field == \"ping\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean_ping\")"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 22 }, "options": { "content": "# Device Temperature" } },
  {
   "title": "Max Temp",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"temp-monitor-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"measurement\")\r\n  |> filter(fn: (r) => r._field == \"temperature\")\r\n  |> max()\r\n  |> yield(name: \"max_temperature_last_hour\")"
    }
   ]
  },
  {
   "title": "Average over 1 minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"temp-monitor-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"measurement\")\r\n  |> filter(fn: (r) => r._field == \"temperature\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean_temperature\")"
    }
   ]
  }
 ]
}